#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

tailscale_warn() {
    echo "tailscale: WARNING:" "$@" >&2
}

copy_exec /usr/sbin/tailscaled /sbin
copy_exec /usr/bin/tailscale /bin
copy_exec $(readlink -f /usr/sbin/iptables) /sbin/iptables
# update-alternatives --set iptables /usr/sbin/iptables-legacy
# update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
# update-alternatives --set arptables /usr/sbin/arptables-legacy
# update-alternatives --set ebtables /usr/sbin/ebtables-legacy
copy_modules_dir kernel/net/ipv6/netfilter
copy_modules_dir kernel/net/ipv4/netfilter
copy_modules_dir kernel/net/netfilter

for so in $(ldconfig -p | sed -nr 's/^\s*libnss_files\.so\.[0-9]+\s.*=>\s*//p'); do
    copy_exec "$so"
done

mkdir -p $DESTDIR/var/lib/tailscale
cp -pr /var/lib/tailscale/tailscaled.state $DESTDIR/var/lib/tailscale

#mkdir $DESTDIR/etc/ssl
cp -prL /etc/ssl $DESTDIR/etc

#home="$(mktemp --directory -- "$DESTDIR/root-XXXXXXXXXX")" # avoid collisions with $rootmnt
#chmod 0700 -- "$home"
#for x in passwd group; do echo "$x: files"; done >"$DESTDIR/etc/nsswitch.conf"
#echo "root:*:0:0::${home#"$DESTDIR"}:/bin/sh" >"$DESTDIR/etc/passwd"
#echo "root:!:0:" >"$DESTDIR/etc/group"

# Copy config and host keys
#mkdir -p -- "$DESTDIR/etc/dropbear"
#if [ -e /etc/dropbear-initramfs/config ]; then
#    cp -pt "$DESTDIR/etc/dropbear" "/etc/dropbear-initramfs/config"
#fi

#copied_hostkey="n"
#for keytype in dss rsa ecdsa ed25519; do
#    hostkey="/etc/dropbear-initramfs/dropbear_${keytype}_host_key"
#    if [ -f "$hostkey" ]; then
#        cp -pt "$DESTDIR/etc/dropbear" "$hostkey"
#        copied_hostkey="y"
#    fi
#done
#if [ "$copied_hostkey" = "n" ]; then
#    dropbear_warn "Missing host keys, SSH login to initramfs won't work!"
#fi

# Copy authorized_keys
#mkdir -m0700 -- "$home/.ssh"
#if [ -e /etc/dropbear-initramfs/authorized_keys ]; then
#    cat /etc/dropbear-initramfs/authorized_keys
#else
#    for keytype in dsa rsa ecdsa ed25519; do
#        pubkey="/etc/dropbear-initramfs/id_${keytype}.pub"
#        if [ -e "$pubkey" ]; then
#            cat "$pubkey"
#        fi
#    done
#fi >"$home/.ssh/authorized_keys"
#
#if ! grep -qE '^([^#]+)?(ssh-(dss|rsa|ed25519)|ecdsa-sha2-nistp(256|384|521)) ' <"$home/.ssh/authorized_keys"; then
#    dropbear_warn "Invalid authorized_keys file, SSH login to initramfs won't work!"
#fi

#/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port 41641

